DEBUG_FUNCTION_CALL = False

MOST_COMMON_WORDS = "most_common_words.csv"
WORDLIST_FILE = "custom_words.csv"
SHOW_TIMES_ENCOUNTERED = True
SHOW_TIMES_CORRECT = True

INVALID_COMMAND_TEXT = "Invalid command..."

NUMBER_OF_SUGGESTIONS = 5
PROBLEM_WORD_THRESHOLD = 0.4

QUIZ_WORD_COLOR = "light_grey"
CORRECT_COLOR = "light_green"
WRONG_COLOR = "red"
MISC_COLOR = "light_blue"
MISC_COLOR2 = "light_red"

MAX_LEVEL = 11
POINTS_TO_LEVEL_UP = 400
POINTS_FOR_CORRECT = 100
POINTS_FOR_COMBO_3 = 300
POINTS_FOR_COMBO_5 = 500
POINTS_FOR_COMBO_10 = 1000
POINTS_RETRACTED_FOR_WRONG = 50


